[[redirects]]
from = "/api/:chapter/:page"
to = "/.netlify/functions/specific?chapter=:chapter&page=:page"
status = 200
force = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
